FROM gcr.io/ossf-malware-analysis/analysis

COPY console_log.py /
# docker run --cgroupns=host --privileged --rm -ti \
#   pa-image analyze -dynamic-bucket file:///results/ \
#   -ecosystem pypi -package pillow -version 10.3.0 > /dev/null 2>&1 \
#   && python3 console_log.py
